name: Deploy to DigitalOcean

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Install Nx CLI globally
        run: npm install -g nx

      - name: Build Angular App
        run: nx build angular-memorial-platform

      - name: Build NestJS App
        run: nx build api --prod

      - name: Deploy Angular App
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          port: ${{ secrets.DO_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: 'dist/apps/angular-memorial-platform/*'
          target: '/home/memorial-platform/htdocs/memorial-platform.pekict.dev'

      - name: Deploy NestJS App
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          port: ${{ secrets.DO_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: 'dist/apps/api/*'
          target: '/home/memorial-platform-api/htdocs/memorial-platform-api.pekict.dev'

      - name: Install PM2
        run: npm install -g pm2@latest

      - name: Restart Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.DO_PORT }}
          script: |
            cd /home/runcloud/webapps/
            pm2 restart api
