name: Deploy to DigitalOcean

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Install Nx CLI globally
        run: npm install -g nx

      - name: Build Angular App
        run: nx build angular-memorial-platform

      - name: Build NestJS App
        run: nx build api

      - name: Deploy Angular App
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          port: ${{ secrets.DO_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: 'dist/apps/angular-memorial-platform/*'
          target: '/var/www/memorial-platform/'

      - name: Deploy NestJS App
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          port: ${{ secrets.DO_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: 'dist/apps/api/*'
          target: '/var/www/memorial-platform-api/'

      - name: Transfer package.json
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          port: ${{ secrets.DO_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: 'package.json'
          target: '/var/www/'

      - name: Install dependencies on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          port: ${{ secrets.DO_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/memorial-platform
            npm install --production
            cd /var/www/memorial-platform-api
            npm install --production
