name: Deploy to My website

on:
  push:
    branches: [ master ]
    
jobs:
  web-deploy:

    name: Deploy Angular App
    runs-on: ubuntu-latest

    steps:
    - name: Get latest code
      uses: actions/checkout@v2.3.2

    - name: Use Node.js 14 LTS
      uses: actions/setup-node@v2
      with:
        node-version: '14'
      
    - name: Install NPM Modules
      run: npm install

    - name: Build Project
      run: npm run build
    
    - name: Upload from public_html via FTP
      uses: airvzxf/ftp-deployment-action@latest
      with:
        server: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local_dir: './dist'
        remote_dir: './public_html/angular'
        delete: 'true'
